#!/usr/bin/env python
"""
citebite utility. Takes a citation as copied from a journal article and returns
a JSON formatted set of data from it.
"""
import sys
import json

import parse


with open(sys.argv[1]) as f:
    data = parse.to_dict(f.read())
    print json.dumps(data, indent=2)
